---
name: Python testing

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7,3.8,3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src/
  
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7,3.8,3.9]

    steps:    
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Test with pytest
        run: |
          pip install pytest
          pytest src/

